### ISSUE TITLE
Solution for not getting videos data:

### ISSUE THREAD

**Issue by Tomato6966** [zyrouge/node-youtube-ext#8]
You are filtering for "HOME" but you should filter for smt where the content is, because the language changes...
`?.find((x) => (x?.tabRenderer?.content))`

**Comment by zyrouge** [comment]
~~where exactly? 🤔~~ Scraping other categories seemed unreliable at the time of making it, I'll look into it again.

**Comment by Tomato6966** [comment]
For me it didnt work because i didnt have home based on my System language
The content tab is just available in the home so thats fine
